import { useState } from "react";
const ApiResponse = [
  {
    name: "Normal",
    price: 230,
    seatRows: {
      A: [
        {
          id: "A1",
          name: "1",
          isSeat: true,
          available: false,
          reserved: true,
        },
        {
          id: "A2",
          name: 2,
          isSeat: true,
          available: false,
          reserved: false,
        },
        {
          id: "A3",
          name: "3",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "A4",
          name: "4",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "A5",
          name: "5",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "A6",
          name: "6",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: null,
          name: null,
          isSeat: false,
          available: false,
          reserved: false,
        },
        {
          id: "A7",
          name: "7",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "A8",
          name: "8",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "A9",
          name: "9",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "A10",
          name: "10",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "A11",
          name: 11,
          isSeat: true,
          available: false,
          reserved: true,
        },
        {
          id: "A12",
          name: 12,
          isSeat: true,
          available: false,
          reserved: true,
        },
        {
          id: "A13",
          name: 13,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "A14",
          name: 14,
          isSeat: true,
          available: false,
          reserved: true,
        },
        {
          id: "A15",
          name: 15,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "A16",
          name: 16,
          isSeat: true,
          available: false,
          reserved: true,
        },
        {
          id: "A17",
          name: 17,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "A18",
          name: 18,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "A19",
          name: 19,
          isSeat: true,
          available: true,
          reserved: false,
        },
      ],
      B: [
        {
          id: "B1",
          name: 1,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B2",
          name: 2,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: null,
          name: null,
          isSeat: false,
          available: true,
          reserved: false,
        },
        {
          id: "B3",
          name: 3,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B4",
          name: 4,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: null,
          name: null,
          isSeat: false,
          available: false,
          reserved: false,
        },
        {
          id: "B5",
          name: 5,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B6",
          name: 6,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B7",
          name: 7,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B8",
          name: 8,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B9",
          name: 9,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: null,
          name: null,
          isSeat: false,
          available: false,
          reserved: false,
        },
        {
          id: null,
          name: null,
          isSeat: false,
          available: false,
          reserved: false,
        },
        {
          id: "B10",
          name: 10,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B11",
          name: 11,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B12",
          name: 12,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B13",
          name: 13,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B14",
          name: 14,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B15",
          name: 15,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B16",
          name: 16,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B17",
          name: 17,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B18",
          name: 18,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B19",
          name: 19,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B20",
          name: 20,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B21",
          name: 21,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B22",
          name: 22,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B23",
          name: 23,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B24",
          name: 24,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B25",
          name: 25,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B26",
          name: 26,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B27",
          name: 27,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B28",
          name: 28,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "B29",
          name: 29,
          isSeat: true,
          available: true,
          reserved: false,
        },
      ],
      C: [
        {
          id: null,
          name: null,
          isSeat: false,
        },
        {
          id: null,
          name: null,
          isSeat: false,
        },
        {
          id: null,
          name: null,
          isSeat: false,
        },
        {
          id: null,
          name: null,
          isSeat: false,
        },
        {
          id: null,
          name: null,
          isSeat: false,
        },
        {
          id: "C1",
          name: 1,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C2",
          name: 2,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C3",
          name: 3,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C4",
          name: 4,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C5",
          name: 5,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C6",
          name: 6,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C7",
          name: 7,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C8",
          name: 8,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C9",
          name: 9,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C10",
          name: 10,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C11",
          name: 11,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C12",
          name: 12,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C13",
          name: 13,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C14",
          name: 14,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C15",
          name: 15,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C16",
          name: 16,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C17",
          name: 17,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C18",
          name: 18,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: null,
          name: null,
          isSeat: false,
        },
        {
          id: null,
          name: null,
          isSeat: false,
        },
        {
          id: "C19",
          name: 19,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C20",
          name: 20,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C21",
          name: 21,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C22",
          name: 22,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C23",
          name: 23,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C24",
          name: 24,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C25",
          name: 25,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C26",
          name: 26,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C27",
          name: 27,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C28",
          name: 28,
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "C29",
          name: 29,
          isSeat: true,
          available: true,
          reserved: false,
        },
      ],
    },
  },
  {
    name: "VIP",
    price: 530,
    seatRows: {
      D: [
        {
          id: "D1",
          name: "1",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "D2",
          name: "2",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "D3",
          name: "3",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "D4",
          name: "4",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "D5",
          name: "5",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "D6",
          name: "6",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "D7",
          name: "7",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "D8",
          name: "8",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "D9",
          name: "9",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "D10",
          name: "10",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "D11",
          name: "11",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "D12",
          name: "12",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "D13",
          name: "13",
          isSeat: true,
          available: true,
          reserved: false,
        },
      ],
      E: [
        {
          id: null,
          name: null,
          isSeat: false,
        },
        {
          id: "E1",
          name: "1",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "E2",
          name: "2",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "E3",
          name: "3",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: null,
          name: null,
          isSeat: false,
        },
      ],
      F: [
        {
          id: "F1",
          name: "1",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "F2",
          name: "2",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "F3",
          name: "3",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "F4",
          name: "4",
          isSeat: true,
          available: true,
          reserved: false,
        },
        {
          id: "F5",
          name: "5",
          isSeat: true,
          available: true,
          reserved: false,
        },
      ],
    },
  },
];

export const useSeatBooking = () => {
  const [selectedSeats, setSelectedSeats] = useState<string[]>([]);

  const handleSeatClick = (seat: string) => {
    if (selectedSeats.includes(seat)) {
      // setAvailableSeats([...availableSeats, seat]);
      setSelectedSeats(
        selectedSeats.filter((reservedSeat) => reservedSeat !== seat),
      );
    } else {
      setSelectedSeats([...selectedSeats, seat]);
    }
  };

  const isSelectedSeat = (seat: string) => {
    return !selectedSeats.includes(seat);
  };

  const handleReservationSubmit = () => {
    console.log("Selected Seats", selectedSeats);
  };

  return {
    isSelectedSeat,
    handleSeatClick,
    selectedSeats,
    handleReservationSubmit,
    ApiResponse,
  };
};

// // import { useState } from "react";

// export type SeatDetail = {
//   seatID: null | string;
//   isSeat: boolean;
//   seatName?: string;
//   status: "Available" | "Booked" | "Reserved" | "Unavailable";
// };

// // export type seatType = {
// //   [key: string]: SeatDetail[];
// // };
// export type SeatRecord = {
//   name: string;
//   price: number;
//   showName: string;
//   row: string;
//   SeatDetails: SeatDetail[][];
// };

// export const useSeatBooking = () => {
//   // const allSeats: SeatRecord[] = [
//   //   {
//   //     name: "Section A",
//   //     price: 200,
//   //     showName: "TestShow",
//   //     row: "A",
//   //     SeatDetails: [
//   //       [
//   //         {
//   //           seatID: "A1",
//   //           isSeat: false,
//   //           seatName: "A",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A1",
//   //           isSeat: true,
//   //           seatName: "1",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A2",
//   //           isSeat: true,
//   //           seatName: "2",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A3",
//   //           isSeat: true,
//   //           seatName: "3",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A4",
//   //           isSeat: true,
//   //           seatName: "4",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A5",
//   //           isSeat: true,
//   //           seatName: "5",
//   //           status: "Available",
//   //         },
//   //       ],
//   //       [
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //       ],
//   //       [
//   //         {
//   //           seatID: "A1",
//   //           isSeat: false,
//   //           seatName: "A",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A1",
//   //           isSeat: true,
//   //           seatName: "1",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A2",
//   //           isSeat: true,
//   //           seatName: "2",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A3",
//   //           isSeat: true,
//   //           seatName: "3",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A4",
//   //           isSeat: true,
//   //           seatName: "4",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A5",
//   //           isSeat: true,
//   //           seatName: "5",
//   //           status: "Available",
//   //         },
//   //       ],
//   //       [
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A6",
//   //           isSeat: false,
//   //           seatName: "B",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A7",
//   //           isSeat: true,
//   //           seatName: "7",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A8",
//   //           isSeat: true,
//   //           seatName: "8",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A9",
//   //           isSeat: true,
//   //           seatName: "9",
//   //           status: "Available",
//   //         },
//   //         {
//   //           seatID: "A10",
//   //           isSeat: true,
//   //           seatName: "10",
//   //           status: "Available",
//   //         },
//   //       ],
//   //     ],
//   //   },
//   // ];

//   const ApiResponse = [
//     {
//       name: "Normal",
//       price: 230,
//       seatRows: {
//         A: [
//           {
//             id: "A1",
//             name: "1",
//             isSeat: true,
//           },
//           {
//             id: null,
//             name: null,
//             isSeat: false,
//           },
//           {
//             id: "A3",
//             name: "3",
//             isSeat: true,
//           },
//           {
//             id: "A4",
//             name: "4",
//             isSeat: true,
//           },
//           {
//             id: "A5",
//             name: "5",
//             isSeat: true,
//           },
//           {
//             id: "A6",
//             name: "6",
//             isSeat: true,
//           },
//           {
//             id: null,
//             name: null,
//             isSeat: false,
//           },
//           {
//             id: "A7",
//             name: "7",
//             isSeat: true,
//           },
//           {
//             id: "A8",
//             name: "8",
//             isSeat: true,
//           },
//           {
//             id: "A9",
//             name: "9",
//             isSeat: true,
//           },
//           {
//             id: "A10",
//             name: "10",
//             isSeat: true,
//           },
//           {
//             id: null,
//             name: null,
//             isSeat: false,
//           },
//           {
//             id: "A11",
//             name: "11",
//             isSeat: true,
//           },
//           {
//             id: "A12",
//             name: "12",
//             isSeat: true,
//           },
//           {
//             id: "A13",
//             name: "13",
//             isSeat: true,
//           },
//           {
//             id: "A10",
//             name: "10",
//             isSeat: true,
//           },
//           {
//             id: null,
//             name: null,
//             isSeat: false,
//           },
//           {
//             id: "A11",
//             name: "11",
//             isSeat: true,
//           },
//           {
//             id: "A12",
//             name: "12",
//             isSeat: true,
//           },
//           {
//             id: "A13",
//             name: "13",
//             isSeat: true,
//           },
//           {
//             id: "A1",
//             name: "1",
//             isSeat: true,
//           },
//           {
//             id: null,
//             name: null,
//             isSeat: false,
//           },
//           {
//             id: "A3",
//             name: "3",
//             isSeat: true,
//           },
//           {
//             id: "A4",
//             name: "4",
//             isSeat: true,
//           },
//           {
//             id: "A5",
//             name: "5",
//             isSeat: true,
//           },
//           {
//             id: "A6",
//             name: "6",
//             isSeat: true,
//           },
//           {
//             id: null,
//             name: null,
//             isSeat: false,
//           },
//           {
//             id: "A7",
//             name: "7",
//             isSeat: true,
//           },
//           {
//             id: "A8",
//             name: "8",
//             isSeat: true,
//           },
//           {
//             id: "A9",
//             name: "9",
//             isSeat: true,
//           },
//           {
//             id: "A10",
//             name: "10",
//             isSeat: true,
//           },
//           {
//             id: null,
//             name: null,
//             isSeat: false,
//           },
//           {
//             id: "A11",
//             name: "11",
//             isSeat: true,
//           },
//           {
//             id: "A12",
//             name: "12",
//             isSeat: true,
//           },
//           {
//             id: "A13",
//             name: "13",
//             isSeat: true,
//           },
//           {
//             id: "A10",
//             name: "10",
//             isSeat: true,
//           },
//           {
//             id: null,
//             name: null,
//             isSeat: false,
//           },
//           {
//             id: "A11",
//             name: "11",
//             isSeat: true,
//           },
//           {
//             id: "A12",
//             name: "12",
//             isSeat: true,
//           },
//           {
//             id: "A13",
//             name: "13",
//             isSeat: true,
//           },
//         ],
//         B: [
//           {
//             id: null,
//             name: null,
//             isSeat: false,
//           },
//           {
//             id: "B2",
//             name: "2",
//             isSeat: true,
//           },
//           {
//             id: "B3",
//             name: "3",
//             isSeat: true,
//           },
//           {
//             id: "B4",
//             name: "4",
//             isSeat: true,
//           },
//           {
//             id: null,
//             name: null,
//             isSeat: false,
//           },
//         ],
//         C: [
//           {
//             id: null,
//             name: null,
//             isSeat: false,
//           },
//           {
//             id: null,
//             name: null,
//             isSeat: false,
//           },
//           {
//             id: "C1",
//             name: "1",
//             isSeat: true,
//           },
//           {
//             id: null,
//             name: null,
//             isSeat: false,
//           },
//           {
//             id: "C2",
//             name: "2",
//             isSeat: true,
//           },
//           {
//             id: "C3",
//             name: "3",
//             isSeat: true,
//           },
//           {
//             id: "C4",
//             name: "4",
//             isSeat: true,
//           },
//           {
//             id: "C5",
//             name: "5",
//             isSeat: false,
//           },
//           {
//             id: null,
//             name: null,
//             isSeat: false,
//           },
//           {
//             id: "C6",
//             name: "6",
//             isSeat: true,
//           },
//         ],
//       },
//     },
//     {
//       name: "VIP",
//       price: 530,
//       seatRows: {
//         D: [
//           {
//             id: "D1",
//             name: "1",
//             isSeat: true,
//           },
//           {
//             id: "D2",
//             name: "2",
//             isSeat: true,
//           },
//           {
//             id: "D3",
//             name: "3",
//             isSeat: true,
//           },
//           {
//             id: "D4",
//             name: "4",
//             isSeat: true,
//           },
//           {
//             id: "D5",
//             name: "5",
//             isSeat: true,
//           },
//           {
//             id: "D6",
//             name: "6",
//             isSeat: true,
//           },
//           {
//             id: "D7",
//             name: "7",
//             isSeat: true,
//           },
//           {
//             id: "D8",
//             name: "8",
//             isSeat: true,
//           },
//           {
//             id: "D9",
//             name: "9",
//             isSeat: true,
//           },
//           {
//             id: "D10",
//             name: "10",
//             isSeat: true,
//           },
//           {
//             id: "D11",
//             name: "11",
//             isSeat: true,
//           },
//           {
//             id: "D12",
//             name: "12",
//             isSeat: true,
//           },
//           {
//             id: "D13",
//             name: "13",
//             isSeat: true,
//           },
//         ],
//         E: [
//           {
//             id: null,
//             name: null,
//             isSeat: false,
//           },
//           {
//             id: "E2",
//             name: "2",
//             isSeat: true,
//           },
//           {
//             id: "E3",
//             name: "3",
//             isSeat: true,
//           },
//           {
//             id: "E4",
//             name: "4",
//             isSeat: true,
//           },
//           {
//             id: null,
//             name: null,
//             isSeat: false,
//           },
//         ],
//         F: [
//           {
//             id: "F1",
//             name: "1",
//             isSeat: true,
//           },
//           {
//             id: "F2",
//             name: "2",
//             isSeat: true,
//           },
//           {
//             id: "F3",
//             name: "3",
//             isSeat: true,
//           },
//           {
//             id: "F4",
//             name: "4",
//             isSeat: true,
//           },
//           {
//             id: "F5",
//             name: "5",
//             isSeat: true,
//           },
//         ],
//       },
//     },
//   ];
//   return {
//     allSeats: ApiResponse,
//   };
// };

// // const allSeats: SeatRecord[] = [
// //   {
// //     name: "Section A",
// //     price: 200,
// //     showName: "TestShow",
// //     row: "A",
// //     SeatDetails: {
// //       A: [
// //         {
// //           seatID: "A1",
// //           isSeat: true,
// //           seatName: "1",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A2",
// //           isSeat: true,
// //           seatName: "2",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A3",
// //           isSeat: true,
// //           seatName: "3",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A4",
// //           isSeat: true,
// //           seatName: "4",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A5",
// //           isSeat: true,
// //           seatName: "5",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A6",
// //           isSeat: true,
// //           seatName: "6",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A7",
// //           isSeat: true,
// //           seatName: "7",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A8",
// //           isSeat: true,
// //           seatName: "8",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A9",
// //           isSeat: true,
// //           seatName: "9",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A10",
// //           isSeat: true,
// //           seatName: "10",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A11",
// //           isSeat: true,
// //           seatName: "11",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A12",
// //           isSeat: true,
// //           seatName: "12",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A13",
// //           isSeat: true,
// //           seatName: "13",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A14",
// //           isSeat: true,
// //           seatName: "14",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A15",
// //           isSeat: true,
// //           seatName: "15",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A16",
// //           isSeat: true,
// //           seatName: "16",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A17",
// //           isSeat: true,
// //           seatName: "17",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A18",
// //           isSeat: true,
// //           seatName: "18",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A19",
// //           isSeat: true,
// //           seatName: "19",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A20",
// //           isSeat: true,
// //           seatName: "8",
// //           status: "Available",
// //         },
// //         {
// //           seatID: " A21",
// //           isSeat: true,
// //           seatName: "21",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A22",
// //           isSeat: true,
// //           seatName: "23",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A24",
// //           isSeat: true,
// //           seatName: "24",
// //           status: "Available",
// //         },
// //         {
// //           seatID: "A15",
// //           isSeat: true,
// //           seatName: "15",
// //           status: "Available",
// //         },
// //       ],
// //     },
// //   },
// // ];
