// import { useState } from "react";

export type SeatDetail = {
  seatID: null | string;
  isSeat: boolean;
  seatName?: string;
  status: "Available" | "Booked" | "Reserved" | "Unavailable";
};

export type SeatRecord = {
  name: string;
  price: number;
  showName: string;
  row: string;
  SeatDetails: SeatDetail[];
};

export const useSeatBooking = () => {
  const allSeats: SeatRecord[] = [
    {
      name: "Section A",
      price: 200,
      showName: "TestShow",
      row: "A",
      SeatDetails: [
        {
          seatID: "A1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "A2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "A3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "A4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "A5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "A6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "A7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "A8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "A9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "A10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "A11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "A12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section B",
      price: 200,
      showName: "TestShow",
      row: "B",
      SeatDetails: [
        {
          seatID: "B1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "B2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "B3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "B4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "B5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "B6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "B7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "B8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "B9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "B10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "B11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "B12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section C",
      price: 200,
      showName: "TestShow",
      row: "C",
      SeatDetails: [
        {
          seatID: "C1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "C2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "C3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "C4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "C5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "C6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "C7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "C8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "C9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "C10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "C11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "C12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section D",
      price: 200,
      showName: "TestShow",
      row: "D",
      SeatDetails: [
        {
          seatID: "D1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "D2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "D3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "D4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "D5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "D6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "D7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "D8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "D9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "D10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "D11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "D12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section E",
      price: 200,
      showName: "TestShow",
      row: "E",
      SeatDetails: [
        {
          seatID: "E1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "E2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "E3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "E4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "E5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "E6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "E7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "E8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "E9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "E10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "E11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "E12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section F",
      price: 200,
      showName: "TestShow",
      row: "F",
      SeatDetails: [
        {
          seatID: "F1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "F2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "F3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "F4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "F5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "F6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "F7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "F8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "F9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "F10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "F11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "F12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section G",
      price: 200,
      showName: "TestShow",
      row: "G",
      SeatDetails: [
        {
          seatID: "G1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "G2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "G3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "G4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "G5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "G6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "G7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "G8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "G9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "G10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "G11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "G12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section H",
      price: 200,
      showName: "TestShow",
      row: "H",
      SeatDetails: [
        {
          seatID: "H1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "H2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "H3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "H4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "H5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "H6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "H7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "H8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "H9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "H10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "H11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "H12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section I",
      price: 200,
      showName: "TestShow",
      row: "I",
      SeatDetails: [
        {
          seatID: "I1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "I2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "I3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "I4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "I5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "I6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "I7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "I8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "I9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "I10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "I11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "I12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section J",
      price: 200,
      showName: "TestShow",
      row: "J",
      SeatDetails: [
        {
          seatID: "J1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "J2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "J3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "J4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "J5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "J6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "J7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "J8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "J9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "J10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "J11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "J12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section K",
      price: 200,
      showName: "TestShow",
      row: "K",
      SeatDetails: [
        {
          seatID: "K1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "K2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "K3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "K4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "K5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "K6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "K7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "K8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "K9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "K10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "K11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "K12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section L",
      price: 200,
      showName: "TestShow",
      row: "L",
      SeatDetails: [
        {
          seatID: "L1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "L2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "L3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "L4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "L5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "L6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "L7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "L8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "L9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "L10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "L11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "L12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section M",
      price: 200,
      showName: "TestShow",
      row: "M",
      SeatDetails: [
        {
          seatID: "M1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "M2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "M3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "M4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "M5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "M6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "M7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "M8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "M9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "M10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "M11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "M12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section N",
      price: 200,
      showName: "TestShow",
      row: "N",
      SeatDetails: [
        {
          seatID: "N1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "N2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "N3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "N4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "N5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "N6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "N7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "N8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "N9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "N10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "N11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "N12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section O",
      price: 200,
      showName: "TestShow",
      row: "O",
      SeatDetails: [
        {
          seatID: "O1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "O2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "O3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "O4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "O5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "O6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "O7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "O8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "O9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "O10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "O11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "O12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section P",
      price: 200,
      showName: "TestShow",
      row: "P",
      SeatDetails: [
        {
          seatID: "P1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "P2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "P3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "P4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "P5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "P6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "P7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "P8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "P9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "P10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "P11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "P12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section Q",
      price: 200,
      showName: "TestShow",
      row: "Q",
      SeatDetails: [
        {
          seatID: "Q1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "Q2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "Q3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "Q4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "Q5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "Q6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "Q7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "Q8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "Q9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "Q10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "Q11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "Q12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section R",
      price: 200,
      showName: "TestShow",
      row: "R",
      SeatDetails: [
        {
          seatID: "R1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "R2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "R3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "R4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "R5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "R6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "R7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "R8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "R9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "R10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "R11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "R12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section S",
      price: 200,
      showName: "TestShow",
      row: "S",
      SeatDetails: [
        {
          seatID: "S1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "S2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "S3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "S4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "S5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "S6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "S7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "S8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "S9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "S10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "S11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "S12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section T",
      price: 200,
      showName: "TestShow",
      row: "T",
      SeatDetails: [
        {
          seatID: "T1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "T2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "T3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "T4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "T5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "T6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "T7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "T8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "T9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "T10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "T11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "T12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section U",
      price: 200,
      showName: "TestShow",
      row: "U",
      SeatDetails: [
        {
          seatID: "U1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "U2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "U3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "U4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "U5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "U6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "U7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "U8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "U9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "U10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "U11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "U12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section V",
      price: 200,
      showName: "TestShow",
      row: "V",
      SeatDetails: [
        {
          seatID: "V1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "V2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "V3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "V4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "V5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "V6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "V7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "V8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "V9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "V10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "V11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "V12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
    {
      name: "Section W",
      price: 200,
      showName: "TestShow",
      row: "W",
      SeatDetails: [
        {
          seatID: "W1",
          isSeat: true,
          seatName: "1",
          status: "Available",
        },
        {
          seatID: "W2",
          isSeat: true,
          seatName: "2",
          status: "Available",
        },
        {
          seatID: "W3",
          isSeat: true,
          seatName: "3",
          status: "Available",
        },
        {
          seatID: "W4",
          isSeat: true,
          seatName: "4",
          status: "Available",
        },
        {
          seatID: "W5",
          isSeat: true,
          seatName: "5",
          status: "Available",
        },
        {
          seatID: "W6",
          isSeat: true,
          seatName: "6",
          status: "Available",
        },
        {
          seatID: "W7",
          isSeat: true,
          seatName: "7",
          status: "Available",
        },
        {
          seatID: "W8",
          isSeat: true,
          seatName: "8",
          status: "Available",
        },
        {
          seatID: "W9",
          isSeat: true,
          seatName: "9",
          status: "Available",
        },
        {
          seatID: "W10",
          isSeat: true,
          seatName: "10",
          status: "Available",
        },
        {
          seatID: "W11",
          isSeat: true,
          seatName: "11",
          status: "Available",
        },
        {
          seatID: "W12",
          isSeat: true,
          seatName: "12",
          status: "Available",
        },
      ],
    },
  ];

  // const [availableSeats, setAvailableSeats] = useState<string[]>([
  //   "A1",
  //   "A2",
  //   "A3",
  //   "A6",
  //   "B1",
  //   "B4",
  //   "B5",
  //   "B6",
  //   "C1",
  //   "C2",
  //   "C3",
  //   "C4",
  //   "C5",
  //   "C6",
  // ]);

  // const [reservedSeats, setReservedSeats] = useState<string[]>([]);
  // const [selectedSeats, setSelectedSeats] = useState<string[]>([
  //   "A4",
  //   "A5",
  //   "B2",
  //   "B3",
  // ]);

  // const handleSeatClick = (seatID: string) => {
  //   if (reservedSeats.includes(seatID)) {
  //     setAvailableSeats([...availableSeats, seatID]);
  //     setReservedSeats(
  //       reservedSeats.filter((reservedSeat) => reservedSeat !== seatID),
  //     );
  //   } else {
  //     setReservedSeats([...reservedSeats, seatID]);
  //     setAvailableSeats(
  //       availableSeats.filter((availableSeat) => availableSeat !== seatID),
  //     );
  //   }
  // };

  // const isSeatAvailable = (seatID: string) => {
  //   return !selectedSeats.includes(seatID);
  // };

  const handleReservationSubmit = () => {
    // setSelectedSeats([...selectedSeats, ...reservedSeats]);
    // setReservedSeats([]);
  };

  return {
    // isSeatAvailable,
    // handleSeatClick,
    // selectedSeats,
    // reservedSeats,
    handleReservationSubmit,
    allSeats,
  };
};

export const ATOZ = [
  {
    name: "Section A",
    price: 200,
    showName: "TestShow",
    row: "A",
    SeatDetails: [
      {
        seatID: "A1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "A2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "A3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "A4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "A5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "A6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "A7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "A8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "A9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "A10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "A11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "A12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section B",
    price: 200,
    showName: "TestShow",
    row: "B",
    SeatDetails: [
      {
        seatID: "B1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "B2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "B3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "B4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "B5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "B6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "B7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "B8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "B9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "B10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "B11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "B12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section C",
    price: 200,
    showName: "TestShow",
    row: "C",
    SeatDetails: [
      {
        seatID: "C1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "C2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "C3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "C4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "C5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "C6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "C7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "C8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "C9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "C10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "C11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "C12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section D",
    price: 200,
    showName: "TestShow",
    row: "D",
    SeatDetails: [
      {
        seatID: "D1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "D2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "D3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "D4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "D5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "D6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "D7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "D8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "D9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "D10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "D11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "D12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section E",
    price: 200,
    showName: "TestShow",
    row: "E",
    SeatDetails: [
      {
        seatID: "E1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "E2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "E3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "E4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "E5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "E6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "E7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "E8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "E9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "E10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "E11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "E12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section F",
    price: 200,
    showName: "TestShow",
    row: "F",
    SeatDetails: [
      {
        seatID: "F1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "F2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "F3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "F4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "F5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "F6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "F7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "F8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "F9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "F10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "F11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "F12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section G",
    price: 200,
    showName: "TestShow",
    row: "G",
    SeatDetails: [
      {
        seatID: "G1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "G2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "G3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "G4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "G5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "G6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "G7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "G8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "G9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "G10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "G11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "G12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section H",
    price: 200,
    showName: "TestShow",
    row: "H",
    SeatDetails: [
      {
        seatID: "H1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "H2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "H3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "H4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "H5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "H6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "H7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "H8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "H9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "H10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "H11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "H12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section I",
    price: 200,
    showName: "TestShow",
    row: "I",
    SeatDetails: [
      {
        seatID: "I1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "I2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "I3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "I4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "I5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "I6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "I7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "I8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "I9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "I10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "I11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "I12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section J",
    price: 200,
    showName: "TestShow",
    row: "J",
    SeatDetails: [
      {
        seatID: "J1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "J2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "J3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "J4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "J5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "J6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "J7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "J8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "J9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "J10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "J11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "J12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section K",
    price: 200,
    showName: "TestShow",
    row: "K",
    SeatDetails: [
      {
        seatID: "K1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "K2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "K3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "K4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "K5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "K6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "K7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "K8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "K9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "K10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "K11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "K12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section L",
    price: 200,
    showName: "TestShow",
    row: "L",
    SeatDetails: [
      {
        seatID: "L1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "L2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "L3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "L4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "L5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "L6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "L7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "L8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "L9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "L10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "L11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "L12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section M",
    price: 200,
    showName: "TestShow",
    row: "M",
    SeatDetails: [
      {
        seatID: "M1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "M2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "M3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "M4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "M5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "M6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "M7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "M8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "M9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "M10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "M11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "M12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section N",
    price: 200,
    showName: "TestShow",
    row: "N",
    SeatDetails: [
      {
        seatID: "N1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "N2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "N3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "N4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "N5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "N6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "N7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "N8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "N9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "N10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "N11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "N12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section O",
    price: 200,
    showName: "TestShow",
    row: "O",
    SeatDetails: [
      {
        seatID: "O1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "O2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "O3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "O4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "O5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "O6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "O7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "O8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "O9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "O10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "O11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "O12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section P",
    price: 200,
    showName: "TestShow",
    row: "P",
    SeatDetails: [
      {
        seatID: "P1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "P2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "P3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "P4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "P5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "P6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "P7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "P8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "P9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "P10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "P11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "P12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section Q",
    price: 200,
    showName: "TestShow",
    row: "Q",
    SeatDetails: [
      {
        seatID: "Q1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "Q2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "Q3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "Q4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "Q5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "Q6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "Q7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "Q8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "Q9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "Q10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "Q11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "Q12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section R",
    price: 200,
    showName: "TestShow",
    row: "R",
    SeatDetails: [
      {
        seatID: "R1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "R2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "R3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "R4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "R5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "R6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "R7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "R8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "R9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "R10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "R11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "R12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section S",
    price: 200,
    showName: "TestShow",
    row: "S",
    SeatDetails: [
      {
        seatID: "S1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "S2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "S3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "S4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "S5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "S6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "S7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "S8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "S9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "S10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "S11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "S12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section T",
    price: 200,
    showName: "TestShow",
    row: "T",
    SeatDetails: [
      {
        seatID: "T1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "T2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "T3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "T4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "T5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "T6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "T7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "T8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "T9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "T10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "T11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "T12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section U",
    price: 200,
    showName: "TestShow",
    row: "U",
    SeatDetails: [
      {
        seatID: "U1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "U2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "U3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "U4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "U5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "U6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "U7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "U8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "U9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "U10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "U11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "U12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section V",
    price: 200,
    showName: "TestShow",
    row: "V",
    SeatDetails: [
      {
        seatID: "V1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "V2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "V3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "V4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "V5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "V6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "V7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "V8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "V9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "V10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "V11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "V12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
  {
    name: "Section W",
    price: 200,
    showName: "TestShow",
    row: "W",
    SeatDetails: [
      {
        seatID: "W1",
        isSeat: true,
        seatName: "1",
        status: "Available",
      },
      {
        seatID: "W2",
        isSeat: true,
        seatName: "2",
        status: "Available",
      },
      {
        seatID: "W3",
        isSeat: true,
        seatName: "3",
        status: "Available",
      },
      {
        seatID: "W4",
        isSeat: true,
        seatName: "4",
        status: "Available",
      },
      {
        seatID: "W5",
        isSeat: true,
        seatName: "5",
        status: "Available",
      },
      {
        seatID: "W6",
        isSeat: true,
        seatName: "6",
        status: "Available",
      },
      {
        seatID: "W7",
        isSeat: true,
        seatName: "7",
        status: "Available",
      },
      {
        seatID: "W8",
        isSeat: true,
        seatName: "8",
        status: "Available",
      },
      {
        seatID: "W9",
        isSeat: true,
        seatName: "9",
        status: "Available",
      },
      {
        seatID: "W10",
        isSeat: true,
        seatName: "10",
        status: "Available",
      },
      {
        seatID: "W11",
        isSeat: true,
        seatName: "11",
        status: "Available",
      },
      {
        seatID: "W12",
        isSeat: true,
        seatName: "12",
        status: "Available",
      },
    ],
  },
];
